# Generated by Django 5.1.3 on 2024-11-26 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
